### ISSUE TITLE
cmake 3.7 build error (add_compile_definitions)

### ISSUE THREAD

**Issue by nunuhara** [kichikuou/xsystem35-sdl2#11]
It looks like `add_compile_definitions` was added in cmake-3.12. So either `cmake_minimum_required` should be increased to 3.12, or the use of this function should be removed.

Note: cmake-3.13 is available via the stretch-backports repo, so it's not a big deal to build on stretch even if you increase the required version.

**Comment by kichikuou** [comment]
Let me set the minimum required version to 3.12 then. Emscripten build also has problems with cmake 3.7, which is a bit cumbersome to fix.
