### ISSUE TITLE
.xsys35rc loading

### ISSUE THREAD

**Issue by nunuhara** [kichikuou/xsystem35-sdl2#14]
Currently, xsystem35 tries to load `$HOME/.xsys35rc` and then `$PWD/.xsys35rc` if it couldn't load the file in `$HOME`.

I would like to change this so that it loads *both* files, with settings in `$PWD/.xsys35rc` overriding settings in `$HOME/.xsy35rc`. This would allow having global settings, which can be overridden for specific games.

What do you think?

**Comment by kichikuou** [comment]
Sounds good, I'm happy to accept a patch. 😀
