### ISSUE TITLE
I tried to create a rance2_en but the game just crash

### ISSUE THREAD

**Issue by fcolecumberri** [kichikuou/xsystem35-sdl2#18]
First of all, this project is amazing, thank you and nunuhara for all of this.

I have just tried to create an AppImage rance2_en with the English patch downloaded from https://alicesoft.fandom.com/wiki/Translation_project using https://github.com/nunuhara/alice-appimage project (which uses this project as backend), but when I run the AppImage I just get:

~~~
(xsystem35:33838): Gtk-CRITICAL **: 15:37:27.687: gtk_widget_set_size_request: assertion 'height >= -1' failed
ev 1100
ev 1100
ev 1100
ev 1100
ev 1100
ev 1100
ev 1100
ev 304
PID(33838), sigsegv caught @ 003, 000dc
Now SDL shutdown ... Done!
~~~

Thanks for all your effort.

**Comment by nunuhara** [comment]
This is an issue with the mkgame.sh script from alice-appimage. It's not copying the files System39.ain/System39.ini when creating the gamedata directory. I will fix the script, but it the meantime you can copy System39.ain and System39.ini into the `games/rance2_en/gamedata/` directory manually. Then you will have to add a line to the file `games/rance2_en/gamedata/xsystem35.gr` for the ain file. It should look like this afterwards:

    ScenarioA RANCE2SA.ALD
    GraphicsA RANCE2GA.ald
    MidiA RANCE2MA.ALD
    WaveA RANCE2WA.ALD
    Ain System39.ain
    SaveA ~/.xsys35/saves/Rance II/Rance IIA.ASD
    SaveB ~/.xsys35/saves/Rance II/Rance IIB.ASD
    SaveC ~/.xsys35/saves/Rance II/Rance IIC.ASD
    SaveD ~/.xsys35/saves/Rance II/Rance IID.ASD
    SaveE ~/.xsys35/saves/Rance II/Rance IIE.ASD
    SaveF ~/.xsys35/saves/Rance II/Rance IIF.ASD
    SaveG ~/.xsys35/saves/Rance II/Rance IIG.ASD
    SaveH ~/.xsys35/saves/Rance II/Rance IIH.ASD
    SaveI ~/.xsys35/saves/Rance II/Rance III.ASD
    SaveJ ~/.xsys35/saves/Rance II/Rance IIJ.ASD

After making these changes, I was able to run the AppImage (at least up to the title menu).

**Comment by nunuhara** [comment]
This is the gdb backtrace for reference. It might be worth adding a check somewhere so that this errors instead of segfaulting.

    Thread 1 "xsystem35" received signal SIGSEGV, Segmentation fault.
    commands2F7C () at .../xsystem35-sdl2/src/cmd2F.c:1331
    1331		sys_addMsg(nact->ain.msg[index]);
    (gdb) bt
    #0  commands2F7C () at .../xsystem35-sdl2/src/cmd2F.c:1331
    #1  0x0000555555592438 in check_command (c0=47) at .../xsystem35-sdl2/src/cmd_check.c:461
    #2  0x0000555555593dfd in nact_main () at .../xsystem35-sdl2/src/nact.c:180
    #3  0x0000555555564326 in main (argc=1, argv=0x7fffffffdbd8) at .../xsystem35-sdl2/src/xsystem35.c:505

**Comment by kichikuou** [comment]
Thanks @nunuhara!
Added a check in a159e7c.

**Comment by fcolecumberri** [comment]
Oh, then sorry I posted an issue on the wrong repo, I already made a pull request with the fixes https://github.com/nunuhara/alice-appimage/pull/2 now I can play rance2_en native on my linux thanks

**Comment by kichikuou** [comment]
Segfaulting was definitely a bug of xsystem35. Thank you for reporting!
