### ISSUE TITLE
HOW TO Load Font for Android/Web

### ISSUE THREAD

**Issue by silas1037** [kichikuou/xsystem35-sdl2#20]
.xsys35rc can only effect on Windows xsys35. When packing in GAMEDATA folder and use zip, it cannot work on Android/Web.

**Comment by kichikuou** [comment]
This should be now fixed both in Web and Android (you can download apk [here](https://github.com/kichikuou/xsystem35-sdl2/actions/runs/902418376)).

Try this: [custom-font-test.zip](https://github.com/kichikuou/xsystem35-sdl2/files/6590836/custom-font-test.zip)
