### ISSUE TITLE
Dialogue text is not getting displayed

### ISSUE THREAD

**Issue by fcolecumberri** [kichikuou/xsystem35-sdl2#21]
![no_text](https://user-images.githubusercontent.com/12193875/122608312-82d4e300-d06b-11eb-9579-35d3042c9882.png)

The text on the fighting menu and the starting menu do appear, but the dialogue's is missing.

I am running on Gentoo/Linux with a just cloned and compiled xsystem35

**Comment by kichikuou** [comment]
Did you run `sudo make install`? It install font files to `/usr/local/share/xsystem35/fonts`, where xsystem35 searches default font files.

Alternatively, you can specify font locations in `.xsys35rc` file. Create `$HOME/.xsys35rc` with the following contents (replace `/home/kichikuou/xsystem35-sdl2` with the directory you cloned `xsystem35-sdl2`):
```
ttfont_gothic: /home/kichikuou/xsystem35-sdl2/fonts/MTLc3m.ttf
ttfont_mincho: /home/kichikuou/xsystem35-sdl2/fonts/mincho.otf
```

**Comment by fcolecumberri** [comment]
Ok, that solved it, I was making a test run
```bash
/path/to/xsystem35
```
now that I installed it, this works, thanks
