### ISSUE TITLE
Disable zen2han_utf8 Converting

### ISSUE THREAD

**Issue by silas1037** [kichikuou/xsystem35-sdl2#22]
Is that okay for me to disable  zen2han_utf8 converting? I wonder why it need to do that, and whether any bugs will happen after removing them, thanks!

**Comment by kichikuou** [comment]
The conversion can be disabled using `ZH 2:` command. You don't have to change xsystem35 code.

**Comment by silas1037** [comment]
> The conversion can be disabled using `ZH 2:` command. You don't have to change xsystem35 code.

Also below 'ZU 1:' in the first ADV file?

**Comment by kichikuou** [comment]
Just below `ZU 1:` would be a good place to put it.

**Comment by silas1037** [comment]
@kichikuou Any way to adjust walking speed faster in Rance IV with xsys35? Just normally in system39 it was well solved.

**Comment by kichikuou** [comment]
I'm not sure what do you mean by "walking speed". In battles?

**Comment by silas1037** [comment]
Well, I mean in the dungeon mouse click and sprite react not so fluent. In system39 original exec it's just like real-time, but in xsys35 you have to click down with 0.5 seconds?

**Comment by kichikuou** [comment]
I see. Since that is a separate issue from this, I created #23.
Let me close this one.
