### ISSUE TITLE
Rance IV: Mouse clicks on maps are not very responsive

### ISSUE THREAD

**Issue by kichikuou** [kichikuou/xsystem35-sdl2#23]
Moved from https://github.com/kichikuou/xsystem35-sdl2/issues/22#issuecomment-877104154.

This issue has existed since the original xsystem35 and is documented in [doc/GAMES.TXT](https://github.com/kichikuou/xsystem35-sdl2/blob/e607c9c2ee2a1c0653f7082137d0fc712bae5b3b/doc/GAMES.TXT#L5-L6).

**Comment by kichikuou** [comment]
@silas1037 This should be fixed now.

**Comment by silas1037** [comment]
Thank you so much! I would like to test it soon~
