### ISSUE TITLE
Can xsystem35-sdl2 play local MP3s as fake "CD Music"?

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/xsystem35-sdl2#26]
I'm wondering if xsystem35-sdl2 can play MP3s as fake "CD Music" like system3-sdl2. If so, could instructions be added to the Read Me?  If not, I'd recommend it as a feature, but there's no hurry. 

I don't need the feature for anything, I'm just summarizing what the tool can do for one of my guides.  If there are any other special features xsystem35-sdl2 can do, besides UTF-8 support which I already know about, feel free to mention them!

**Comment by RottenBlock** [comment]
Ah, great, that should cover it, then!

**Comment by kichikuou** [comment]
With ae30b73, this is now documented in README.md.
