### ISSUE TITLE
Rance 5D closes instantly

### ISSUE THREAD

**Issue by Gygarde** [kichikuou/xsystem35-sdl2#27]
Hello!

I was trying to add the unicode, but then tried with a clean version (without any modification) and it just closed anyway.

Do you know what can I do?

Thank you!

**Comment by kichikuou** [comment]
Hi,

In my environment, xsystem35-sdl2 was able to run Rance 5D (Japanese version). Here's what I did:

1. Install `xsystem35-2.0.1-64bit.exe` downloadable [here](https://github.com/kichikuou/xsystem35-sdl2/releases/tag/win-2.0.1).
2. Copy the `GAMEDATA` folder of Rance 5D CD-ROM to a harddrive. The contents of the folder looks like this:
![rance5d-folder](https://user-images.githubusercontent.com/12679772/139844805-5bfcf28d-97fa-4188-b667-3facaf40f1e6.png)
3. Launch xsystem35 from the desktop icon. It opens a folder chooser. Select the `GAMEDATA` folder created in step 1.
4. The game starts.

Are there anything different from your procedure?

**Comment by kichikuou** [comment]
Ah okay, MangaGamer version. It's actually different in many ways.

I have made some fixes and now it at least boots without crashing. It's not released yet, but if you want to try you can download it from [here](https://github.com/kichikuou/xsystem35-sdl2/actions/runs/1416634832).

**Comment by Gygarde** [comment]
It works! Thank you! Now I tried to add the unicode, but... 
![imagen](https://user-images.githubusercontent.com/38927751/140100835-8ba4626b-2508-4423-b57d-ac4c37876f64.png)

It changed ú for symbols.

![imagen](https://user-images.githubusercontent.com/38927751/140101066-e0009568-e872-4a1f-862f-eee7b874e832.png)
That's English, but...

**Comment by kichikuou** [comment]
Oops, that was a bug. It should be fixed in the latest build (downloadable [here](https://github.com/kichikuou/xsystem35-sdl2/actions/runs/1420298980)).

Please remember to prepare a font when you use non-(Japanese/English) chatacters, as noted [here](https://github.com/kichikuou/xsys35c/blob/master/docs/unicode.adoc#fonts).

**Comment by Gygarde** [comment]
I reinstalled and tried again, with the font in the tutorial too. Also deleted the save file, repacked scenario file again. This only happens with 5D.
![imagen](https://user-images.githubusercontent.com/38927751/140380648-fb1e8be9-9913-4291-b7af-b97043caf762.png)

**Comment by kichikuou** [comment]
What version of xsys35c are you using? If it's not 1.8.0, please update it.

If you are already using 1.8.0, please tell me exactly what changes you made to the decompiled files, so that I can reproduce the issue.

**Comment by Gygarde** [comment]
Oh, didn't notice the new version. I updated and now everything works perfectly. Thank you!
