### ISSUE TITLE
Wrong Music in Kichikuou

### ISSUE THREAD

**Issue by Axiom20** [kichikuou/xsystem35-sdl2#32]
Hello!

I was playing Kichikuou Rance on Android and I noticed that it sometimes played the wrong music. For example when Ex attacks it should've played the Rebellion OST but somehow it's Rance (My glorious days) Theme that plays. I've tried reinstalling and it's still the same, is it normal or not?

**Comment by kichikuou** [comment]
Thanks, I was able to reproduce the issue.

It looks like a bug of `SR` command in xsystem35-sdl2. I'll try to get it fixed this weekend.

**Comment by kichikuou** [comment]
Fixed in [v2.4.0](https://github.com/kichikuou/xsystem35-sdl2/releases/tag/v2.4.0).

**Comment by Axiom20** [comment]
> Thanks, I was able to reproduce the issue.
> 
> It looks like a bug of `SR` command in xsystem35-sdl2. I'll try to get it fixed this weekend.
 


> Fixed in [v2.4.0](https://github.com/kichikuou/xsystem35-sdl2/releases/tag/v2.4.0).

Thank you! It's working perfectly, sorry for the late response.
