### ISSUE TITLE
Rance 4 v2.05 Instant Movement in Rooms

### ISSUE THREAD

**Issue by RottenBlock** [kichikuou/xsystem35-sdl2#35]
### Environment
 - xsystem35 version: 2.7.0, online or offline
 - OS: Windows 11

### Steps to reproduce the behavior
1. Enter any room Rance can walk around in.
2. Click or use the mouse keys to move.

### Expected behavior
Rance should animate being moved from square to square as with the normal executable.

### Actual behavior
Rance instantly teleports to the location of any mouse click, or zips to the nearest wall or object in the direction of a key-press.

### Additional context
This does not happen in vanilla Rance IV.

I realize you may have done this to get the game running, but I hope there's some way to fix it.

**Comment by kichikuou** [comment]
It should be fixed now.

Thanks for the report, let me know of any other glitches you notice!
