### ISSUE TITLE
Feature request: force integer scaling, font select, backlog, pause.

### ISSUE THREAD

**Issue by Lemonov-S** [kichikuou/xsystem35-sdl2#38]
Pretty much this. Don't know if all of this is possible, but it would make the game experience so much nicer.

**Comment by kichikuou** [comment]
#### force integer scaling
This has been available for a while with the `-integerscale` command line option, but in version 2.10.1 it's now selectable from the window menu.

#### font select
You can change the font using the method described in the [last paragraph here](https://github.com/kichikuou/xsys35c/blob/master/docs/unicode.adoc#fonts). Unfortunately, it is not possible to use fonts installed in the OS.

#### backlog
The backlog feature is available in the [browser version](https://kichikuou.github.io/web/). There are currently no plans to offer this on other platforms. The challenge is that we have to implement the UI for each platform.

#### pause
What does this mean?
