### ISSUE TITLE
I can't get the music to work

### ISSUE THREAD

**Issue by fcolecumberri** [kichikuou/xsystem35-sdl2#39]
### Environment
 - xsystem35 version: 2.9.1
 - OS: Arch/Linux with pipewire.

### Steps to reproduce the behavior
1. Download Rance III from haniwa.technology (this also happens with other games)
2. `mkdir BGM` inserted the .mp3 in the BGM directory
3. `find BGM > playlist.txt`
4. `xsystem35` and play the game.

### Expected behavior
Music.

### Actual behavior
No music.

### Additional context
When the `xsystem35` starts, it prints
`cdrom: Loaded playlist from playlist.txt`

The game reproduces sounds (like attacks).

**Comment by kichikuou** [comment]
Rance III's music is MIDI, contained in `RANCE3MA.ALD`. You don't need to prepare a BGM directory. Instead, to get MIDI working on Linux you need to install a soundfont and set the `SDL_SOUNDFONTS` environment variable. For example:

```
$ export SDL_SOUNDFONTS=/usr/share/soundfonts/FluidR3_GM.sf2
$ cd rance3
$ xsystem35
```

See also: https://wiki.archlinux.org/title/FluidSynth

**Comment by fcolecumberri** [comment]
Thanks it worked.

Just as a small detail for future people coming here, for some reason the fluid soundfonts does not sound well, the soundfont-generaluser sounded better.
