### ISSUE TITLE
Unexpected pauses and wrong text in Rance IV

### ISSUE THREAD

**Issue by nunuhara** [kichikuou/xsystem35-sdl2#4]
This code seems to be executed too often:

https://github.com/kichikuou/xsystem35-sdl2/blob/fa790cdcbd9bfea4395215496602efca7c0874b3/src/message.c#L114-L117

The problem is especially noticeable in the English translation of Rance IV, but it also happens in the Japanese version. To reproduce the issue, simply open Rance IV. Normally this should take you immediately to the menu (assuming you've already watched the opening), but what actually happens is the game pauses and you have to click to make the menu show up. After clicking, the text in the message box at the bottom is replaced by 「オープニング」 i.e. the text of the first item in the menu.

![1](https://user-images.githubusercontent.com/52369405/60668325-8d672500-9e20-11e9-9c10-1505180e324f.png)
![2](https://user-images.githubusercontent.com/52369405/60668334-90faac00-9e20-11e9-91ce-812b1f9295e7.png)

I looked into this a bit and I suspect the issue is that the `nextLineIsAfterKaigyou` flag is not reset in `msg_setMessageLocation`. I don't think it makes sense to call `msg_nextPage` after the message location has been changed. That's probably why the wrong text shows up.

**Comment by kichikuou** [comment]
Great find, resetting `nextLineIsAfterKaigyou` in `msg_setMessageLocation` seems to be the right fix.
