### ISSUE TITLE
[Gameplay] 大悪司 DL version, mixing save files will unlock new game+ from the start

### ISSUE THREAD

**Issue by ck1521** [kichikuou/xsystem35-sdl2#41]
Related Version: [v2.9.1](https://github.com/kichikuou/xsystem35-sdl2/releases/tag/v2.9.1l)

Importance: Not important

Issue:
When you have the save file (大悪司SZ.ASD) from the DL version, 
the following options will be available in the first playthrough, before beating the game.

**変化をつける
知り合いを登場させる
女の子海賊隊と対決**
全国集まる強者　**7名**まで

~~（何で肝心の羽黒いない？）~~

![2](https://github.com/kichikuou/xsystem35-sdl2/assets/10858385/352388b3-0f1c-483c-876f-e4930377aded)

I tried load with the same save file with system39 5.50 (the DL version), the new game+ options didn't show up.
Attached 大悪司SZ.ASD from both System39 5.50 and XSystem35
(both from clean start, saved at round 1)
[大悪司.zip](https://github.com/kichikuou/xsystem35-sdl2/files/13615590/default.zip)
I can provide other files from DL versions too if you need.

**Comment by kichikuou** [comment]
Thanks for the report!
There seems to be a bug in the save file encryption code, making the save files non-interoperable with system3.9.
