### ISSUE TITLE
[Gameplay] 大悪司 DL version missing items

### ISSUE THREAD

**Issue by ck1521** [kichikuou/xsystem35-sdl2#42]
Related Version: [v2.9.1](https://github.com/kichikuou/xsystem35-sdl2/releases/tag/v2.9.1l)

Issue:
1. たんたん屋 only sells 2 items (missing 万歳ももんが and 根性入り袋)
![tantan](https://github.com/kichikuou/xsystem35-sdl2/assets/10858385/5dbae091-57b2-470a-ad89-d181a1917292)

2. With debug mode on ([改造ツール](http://65535.nahi.to/sdbbs/index.cgi/img/index.cgi?mode=view&no=114&cpass=)), try getting all the items, half of them seem missing.

XSystem35:
![All Items (X)](https://github.com/kichikuou/xsystem35-sdl2/assets/10858385/07ca8384-b14b-4f90-b32b-84e916870e22)

DL version (System39 5.50):
![All Items (DL)](https://github.com/kichikuou/xsystem35-sdl2/assets/10858385/0f34be2c-f6c4-4660-a5c7-3a12fbb9aa69)

ちなみに悪司と衣笠はめちゃ強くなった (overflow?)
![Super](https://github.com/kichikuou/xsystem35-sdl2/assets/10858385/8f681d6e-02f7-48ff-bcba-fa1ef24b69ca)

**Comment by ck1521** [comment]
Attached the script file from DL version (both with and without debug mode)
[大悪司SA.zip](https://github.com/kichikuou/xsystem35-sdl2/files/13617115/SA.zip)

**Comment by kichikuou** [comment]
Have you loaded a file saved with system3.9 with xsystem35 or vice versa?
The bug in #41 seems to affect not only 大悪司SZ.ASD but also regular save files.

**Comment by ck1521** [comment]
> Have you loaded a file saved with system3.9 with xsystem35 or vice versa? The bug in #41 seems to affect not only 大悪司SZ.ASD but also regular save files.

Yes I found this issue initially by loading my save file from DL version, then noticed items I bought previously now missing.
I didn't notice any other issue yet.

Oh I haven't made any saves (except testing ones) with xsystem35 yet.

**Comment by ck1521** [comment]
Oh nope, I remembered I have made saves on my android, although the export zip file seems to have a bit encoding issue.
![1](https://github.com/kichikuou/xsystem35-sdl2/assets/10858385/fc6b76a5-f75e-4ea5-a0cc-797752382c8b)

"大悪司" likely became "ｴ厖ｾsk" for several files
(I tried opening this zip with SHIFT-JIS, the file names remain the same.)

I fixed the file names, loaded them with System39 5.50 and found the following issues:

1. If you click a region in the event phase, it might crash the game.
2. Some character data seem corrupted.
![2](https://github.com/kichikuou/xsystem35-sdl2/assets/10858385/34a7d79f-3a39-48a7-a123-9eb3221b2d93)

I guess both are result from data sturcture differences.
Attaching my saves from xsystem35 android version.
[savedata.zip](https://github.com/kichikuou/xsystem35-sdl2/files/13622517/savedata.zip)

**Comment by ck1521** [comment]
> Have you loaded a file saved with system3.9 with xsystem35 or vice versa? The bug in #41 seems to affect not only 大悪司SZ.ASD but also regular save files.

I deleted all existing ASD files (including SZ and MsgSkip.asd) and restarted the game, the items are normal now.
I guess this is the same issue with #41

**Comment by kichikuou** [comment]
I just released [2.10.0](https://github.com/kichikuou/xsystem35-sdl2/releases/tag/v2.10.0) that fixes #41.

For Android, try uninstalling and re-installing xsystem35 (to delete existing save files). Unfortunately I could not reproduce the garbled file names issue of exported save data on my end.

If you still have any issues, please let me know.
