### ISSUE TITLE
[Gameplay] 大悪司 DL version, required to install disk 2 on 35年3月1週

### ISSUE THREAD

**Issue by ck1521** [kichikuou/xsystem35-sdl2#43]
Related version: [v2.10.0](https://github.com/kichikuou/xsystem35-sdl2/releases/tag/v2.10.0)

![1](https://github.com/kichikuou/xsystem35-sdl2/assets/10858385/77cf4764-7bd7-4a0c-86cc-0297ffb9a616)
It seems happen on specific date or event. I tried loading saves before this turn and played, no problem.

Loading the same save file with System39, and the starting event is 大杉剛 joining 悪司
![2](https://github.com/kichikuou/xsystem35-sdl2/assets/10858385/02a62036-8bad-4c46-9990-34d3879f3115)

Attaching my save files (all the way from System39 5.50, no modification from XSystem35)
[SaveBackup.zip](https://github.com/kichikuou/xsystem35-sdl2/files/13622715/SaveBackup.zip)

I'll see if I can get the same error if I play right from the start with XSystem35 all the way.
-- Yes it does. Clean start (all .asd files deleted), doing almost nothing, on 35年3月1週 it will require you to install disk 2.
Attaching save files from XSystem35 (save on every turn)
[XSys35.zip](https://github.com/kichikuou/xsystem35-sdl2/files/13622732/XSys35.zip)

**Comment by kichikuou** [comment]
I have re-uploaded the [2.10.0](https://github.com/kichikuou/xsystem35-sdl2/releases/tag/v2.10.0-hotfix1) binary ("hotfix1") with the fix.
