### ISSUE TITLE
Rance 5D black screen

### ISSUE THREAD

**Issue by linakima** [kichikuou/xsystem35-sdl2#45]
### Environment
 - xsystem35 version: 2.11.0
 - OS: Windows 10 x64

### Steps to reproduce the behavior

1. Run xsystem35-x32 or x64
2. Get a black screen

### Actual behavior
video:
https://www.youtube.com/watch?v=CfIRWotyQEY
[DxDiag.txt](https://github.com/kichikuou/xsystem35-sdl2/files/14314911/DxDiag.txt)

**Comment by kichikuou** [comment]
It looks like a regression by commit 50d7d7ee33e07f0e93666b3a72a0724f6613aef1.

**Comment by linakima** [comment]
@kichikuou I was able to run the game on xsystem35 v2.6.0 (x64 and x32)
Does this version support the .xsys35rc file to translate the game using the utf-8 encoding and my own font?

**Comment by kichikuou** [comment]
I will make a fix and release version 2.11.1 soon. Please wait for it.

**Comment by kichikuou** [comment]
Fixed in [v2.11.1](https://github.com/kichikuou/xsystem35-sdl2/releases/tag/v2.11.1).
