### ISSUE TITLE
Rance 5d still stuck on black screen on android

### ISSUE THREAD

**Issue by KaroNiko** [kichikuou/xsystem35-sdl2#46]
In truth, even on version 2.11.1 for android, MG's Rance 5d still does not work.
One minute after startup, a message appears as in the picture and a music starts in the background, but then everything stays still on black screen. I recommend to check again.
Thanks and regards.

![IMG_20240321_082529](https://github.com/kichikuou/xsystem35-sdl2/assets/163753361/c20025b2-661a-4979-b7dd-a9f7042c6687)

**Comment by kichikuou** [comment]
This will be fixed in the next release. If you want to try it out right away, you can download an apk [here](https://github.com/kichikuou/xsystem35-sdl2/actions/runs/9201044264).
