### ISSUE TITLE
Kaeru Nyo Panyo-n (EN patched) without BGI visible on Android. 

### ISSUE THREAD

**Issue by KaroNiko** [kichikuou/xsystem35-sdl2#47]
When starting the game from the initial menu (this okay as in photo), some background images are not loaded, and afterwards not even the character sprites.
Thanks for your attention.

![1711023775637](https://github.com/kichikuou/xsystem35-sdl2/assets/163753361/ffea37fd-d7d4-450a-ac97-0d37e69ddd2e)

**Comment by kichikuou** [comment]
Could you try again with the latest version?

V2.11.2 [fixed](https://github.com/kichikuou/xsystem35-sdl2/commit/7c7768fba414ff6528f258844d5de5dfc12ab82b) a bug where map files of Kaeru Nyo could not be read in some cases.

**Comment by KaroNiko** [comment]
Nah, unfortunately even with the latest version the game has the same problem: invisible sprites and certain missing images.. 🤷

**Comment by KaroNiko** [comment]
Since pictures are more eloquent than words:

![1716547198202](https://github.com/kichikuou/xsystem35-sdl2/assets/163753361/83df29ea-904b-4c95-82c9-c6ce26fa493b)
![1716544354376](https://github.com/kichikuou/xsystem35-sdl2/assets/163753361/2d8539e6-85b6-4294-8c82-406d6bf69d69)
![1716544436081](https://github.com/kichikuou/xsystem35-sdl2/assets/163753361/81b668c6-919c-4ab7-ae85-7deedd1843f5)

I should add that I did not uninstall the previous apk, but overwrote it with the newer one, as you suggested. Otherwise I would have lost all the installed games (in spite of some titles, all in English). Could the issue be because I did not uninstall the previous one, or because there are too many titles present? 
Otherwise to hell with it, I'll do without.

Changing the subject, had you read about the issue concerning MG' Rance 6? I saw that you didn't comment that thread...
Thank you for your interest, chief. 😉

**Comment by kichikuou** [comment]
I remembered that the fix in v2.11.2 do not affect already installed games.

You don't need to uninstall the xsystem35 app, but try installing Kaeru Nyo Panyo-n again from the ZIP. (Already installed games can be removed by long pressing in the menu.)

I was aware of the issue in xsystem4-android with MG Rance 6, but it took me a long time to investigate because of the complexity of the cause.

**Comment by KaroNiko** [comment]
Good news. I uninstalled the game as you suggested and reinstalled it again: now it works perfectly and nothing is missing. 👍
