### ISSUE TITLE
Stretched screen for Kichikou Rance on android

### ISSUE THREAD

**Issue by KaroNiko** [kichikuou/xsystem35-sdl2#48]
While all the other games I have tried maintain the original aspect ratio, this game comes out stretched to fill the screen, without the presence of the black bands on the side. Can this be remedied? Thank you.

![IMG_20240321_155513](https://github.com/kichikuou/xsystem35-sdl2/assets/163753361/bcb43b38-e2eb-4cdf-9445-bcc29be1366d)

**Comment by kichikuou** [comment]
Your screen appears to be displayed correctly. The KR's screen size is 640x400 while most other games are 640x480. 

One problem is that if your device's screen ratio is exactly 16:10, there is no black bands for right-clicking. In that case, you can right-click by touching with two fingers.
