### ISSUE TITLE
Build failures in NIGHTDLL and ShSound modules

### ISSUE THREAD

**Issue by nunuhara** [kichikuou/xsystem35-sdl2#5]
`SYSTEMCOUNTER_MAINLOOP` is undefined:
https://github.com/kichikuou/xsystem35-sdl2/blob/fa790cdcbd9bfea4395215496602efca7c0874b3/modules/NIGHTDLL/nt_scenario.c#L75-L80

`MIX_CD` is undefined:
https://github.com/kichikuou/xsystem35-sdl2/blob/fa790cdcbd9bfea4395215496602efca7c0874b3/modules/NIGHTDLL/nt_sound.c#L30-L40

The ShSound module #includes "wavfile.h" and "pcmlib.h" which have been removed.

It seems NIGHTDLL is used by 夜が来る and ShSound is used by 大悪司.

**Comment by kichikuou** [comment]
In the `emscripten` branch, files under `modules/` are currently unmaintained (because emscripten doesn't support shared libraries). I'm hoping to fix it someday, but it's not a high priority.

You can build the `master` branch if you need those modules, although it doesn't include recent bug fixes.

**Comment by nunuhara** [comment]
In that case, it's probably best to remove at least those two modules from the build system, since they cause a failure when following the instructions in the README.

**Comment by kichikuou** [comment]
[Updated](https://github.com/kichikuou/xsystem35-sdl2/commit/f66e998b208ee794d73ee88f98b4c748a5a955fe) the build instruction. Will do code cleanup later.

**Comment by kichikuou** [comment]
Now these modules successfully build in `emscripten` branch HEAD.

**Comment by nunuhara** [comment]
I get the following error when building this on linux:

    /usr/bin/ld: ../lib/libgraph.a(gre_blend.c.o): relocation R_X86_64_PC32 against undefined symbol `nact' can not be used when making a shared object; recompile with -fPIC

...and a bunch of variations of the same error.

Adding `set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")` in `modules/CMakeLists.txt` fixes the issue, but that should probably be hidden behind a conditional.

Otherwise it works great. I can finally play 大悪司 without booting a VM. Thank you!

**Comment by kichikuou** [comment]
Oops, 19296d9 should fix that.
