### ISSUE TITLE
.xsys35rc in the folder within a zip doesn't work on Android

### ISSUE THREAD

**Issue by 435qb** [kichikuou/xsystem35-sdl2#51]
I'm not sure if this is a bug, but the behavior is inconsistent with the web.

### Environment
 - xsystem35 version:v2.11.1
 - OS:Android

### Steps to reproduce the behavior
Create a zip with a folder contains .xsys35rc
[custom-font-test-in-folder.zip](https://github.com/kichikuou/xsystem35-sdl2/files/14905536/custom-font-test-in-folder.zip)
install this and font config won't work(but it works in web)

**Comment by kichikuou** [comment]
Fixed in v2.11.2. Thanks for the report!
