### ISSUE TITLE
Question: Hide Top Bar?

### ISSUE THREAD

**Issue by VahnFannel** [kichikuou/xsystem35-sdl2#53]
Is it possible to hide the top bar (the one with "File", "Display", etc.) when I'm playing?

![Captura de pantalla (3537)](https://github.com/kichikuou/xsystem35-sdl2/assets/166946923/dcc60629-a047-41b1-9ebf-9db7f75bfecc)

Sorry if this is a dumb question, but I haven't been able to find anywhere if it's possible and how.

Note: I am playing on Windows 10.

**Comment by kichikuou** [comment]
Do you mean in full screen mode? It's not possible right now, but it doesn't seem too difficult to implement. I'll give it a try when I have time.

**Comment by VahnFannel** [comment]
Oh, ok. Thanks for your answer and for your great work! ^^

**Comment by kichikuou** [comment]
Fixed in v2.11.4.
