### ISSUE TITLE
The intro in Rance III has unreadable text

### ISSUE THREAD

**Issue by rafallagow** [kichikuou/xsystem35-sdl2#54]
### Environment
 - xsystem35 version: 2.11.3
 - OS: Windows 10

Clean Rance III+ installation (I followed the wiki https://alicesoft.fandom.com/wiki/User_blog:SupremeJUMBO/Rance_III%2B)

Using the regular system39.exe works fine and the text during the intro is readable.
I also tested Rance IV and there the intro text looks normal with xsystem35.

Edit: I just tried Rance III (without the III+ fan patch) and I see the same issue with xsystem35.

![image](https://github.com/kichikuou/xsystem35-sdl2/assets/17130969/5bbcb820-62c4-4e67-9489-7cbe367508cb)

**Comment by kichikuou** [comment]
Fixed in 2.11.4.

The text in that scene looks a bit ugly because anti-aliasing had to be disabled, but it is better than unreadable.
