### ISSUE TITLE
fileCheckExist command does not work

### ISSUE THREAD

**Issue by SupremeJUMBO** [kichikuou/xsystem35-sdl2#55]
### Environment
 - xsystem35 version: 2.10
 - OS: Windows 10

Hello Kichikuou! I've run into a bug with the fileCheckExist command. I was attempting to check for a save file in slot 1/Autosave slot, then display a splash screen with tips for new players if the file does not exist. However, the command kept returning True/RND = 1, even when there was no save file. I tried a fake file name to test it, and it still returned True as if the file was there. When I run Kichikuou Rance through System39.exe, the command works correctly. The issue only occurs when using xsystem35. Thanks for all your hard work! 

![image](https://github.com/kichikuou/xsystem35-sdl2/assets/156861343/9abe9de1-0442-4e97-9f7c-08cb4204d446)

**Comment by kichikuou** [comment]
Thanks for the report. It will be fixed in the next release.

In the meantime, you can use the `LT 1` command to check for the existence of the save in slot 1.
