### ISSUE TITLE
Error while right-clicking in kichikuou rance 

### ISSUE THREAD

**Issue by BeholdTheBiscuit** [kichikuou/xsystem35-sdl2#58]
### Environment
 - xsystem35 version: 2.11.6
 - OS: Android

### Steps to reproduce the behavior
1. Save in kichikuou rance
2. right click. Or, if it does work correctly (very rarely), right click again.

### Steps to reproduce the behavior
1. While in any fight, right click.
2. Right click again.

### Expected behavior

Exit the drop-down menu or save menu without throwing errors.

### Actual behavior
An error pops up saying undefined command, in all cases. Here's a screenshot.
![Screenshot_20241110_140558_xsystem35](https://github.com/user-attachments/assets/bfeb018a-8632-423c-be50-b74a12b89db7)

### Additional context
After trying a few times, it seems that it will very, very rarely work, exiting the drop down menu without causing errors.

**Comment by kichikuou** [comment]
- Is it the plain Arunaru translation (`KICHIKUSA.ALD` is 2,424,848 bytes) or are you using some mod?
- I suspect that the game file (`KICHIKUSA.ALD`) is corrupted. If possible, try downloading and installing the game again.

**Comment by BeholdTheBiscuit** [comment]
There is no mod, and I've tried downloading from both hsuki and the first result on google (of course I extracted the file and then made the folder a zip file so that I could install the game, I had troubles finding a non-rar file).

**Comment by kichikuou** [comment]
Hmm, I can't reproduce the problem on my end.

Does the error occur if you start from scratch without loading a save? (To make sure it's not caused by a corrupted save)

**Comment by BeholdTheBiscuit** [comment]
It does. I noticed the error number changed now too in the save screen, 033,00002. It's the same every time I start from scratch and save.

**Comment by BeholdTheBiscuit** [comment]
I just found out what it was, I was tapping with two fingers on the game screen for the right click instead of tapping the black bars... I must have done that instincitvely and I was convinced it was that how you right click. *facepalms*. Sorry for the trouble, man. Though I think the app should be able to handle two finger pressing and tapping even if it didn't do anything at all...

**Comment by kichikuou** [comment]
Thank you for following up, and I appreciate the detailed information.

I was able to reproduce the issue on my end - I had overlooked that right-clicking could be triggered with two fingers. It's clear that there is something unusual happening here, so I'll investigate the cause and work on a fix.

**Comment by kichikuou** [comment]
Fixed in version 2.11.7.
