### ISSUE TITLE
use xsystem35 running 妻みぐい２ unable to play beginning CG animation

### ISSUE THREAD

**Issue by russianblue11** [kichikuou/xsystem35-sdl2#59]
- OS:window10
妻みぐい２

If use original System39.exe there will be an CG animation between the beginning sister&brother scene and the after in the train scene.

but use xsystem35 there will not the CG, game will jump to the in the train scene from the sister&brother scene.

**Comment by kichikuou** [comment]
Fixed in version 2.12.0.

**Comment by russianblue11** [comment]
thanks a lot

**Comment by russianblue11** [comment]
The CG can play by using version 2.12.0, but no sound in the entire game.
(Sorry, I misremembered it before. the CG isn't between the beginning sister&brother scene and the after in the train scene. It's after the train scene.)

**Comment by russianblue11** [comment]
sorry the no sound in the entire game question is because my wrong audio setup.

**Comment by kichikuou** [comment]
Good. Have all your problems been resolved?

**Comment by russianblue11** [comment]
Thanks for reply, the CG problem and the no sound problem have been solved.
