### ISSUE TITLE
ALICEの館４・５・６

### ISSUE THREAD

**Issue by linakima** [kichikuou/xsystem35-sdl2#60]
### Environment
 - xsystem35 version: v2.12.0
 - OS: Windows 10 x64

I can't to run any game from [ALICEの館４・５・６](https://pixeldrain.com/u/FLYg98Ab) using the xsystem35-2.12.0 version. 
I receive the error "Unable to continue code execution because the system did not find libportmidi.dll." 
However, the games run without any issues when using xsystem35-v2.11.6

**Comment by kichikuou** [comment]
Fixed in version 2.12.1.
