### ISSUE TITLE
妻みぐい２ Day 18 night game crashes (suddenly quit)

### ISSUE THREAD

**Issue by russianblue11** [kichikuou/xsystem35-sdl2#61]
### Environment
 - OS:windows 10
you can use this save file(csleep.asd) to test,
load, chose 自宅 or なつめ then left-click until game reaches the 優樹 不滿度 screen.
Sometimes the game will crash(suddenly quit) sometimes it doesn't.

[csleep.zip](https://github.com/user-attachments/files/18052816/csleep.zip)

**Comment by kichikuou** [comment]
This will be fixed in the next release. In the meantime, you can download an unreleased build with the fix [here](https://github.com/kichikuou/xsystem35-sdl2/actions/runs/12234745654).

**Comment by russianblue11** [comment]
Thanks a lot.
